build:
    zip:
        pack:
            excludes:
                paths:
                    - .gitignore
                    - .github
                    - .git
                    - bin
                    - images
                    - node_modules
                    - tests
                    - ecs.php
                    - phpunit.xml.dist
                    - package.json
                    - package-lock.json
                    - .eslintignore
                    - .eslintrc-administration.js
                    - .eslintrc-storefront.js
                    - "*.zip"
                    - "*.DS_Store"
                    - dependencies
                    - vendor/nosto/shopware6-job-scheduler/.idea
                    - vendor/nosto/shopware6-job-scheduler/.github
                    - vendor/nosto/shopware6-job-scheduler/node_modules
