build:
    shopwareVersionConstraint: "^6.5.4"

    zip:
        composer:
            before_hooks:
                - jq '.repositories[0].options.symlink = false' composer.json > temp.json && mv temp.json composer.json
                - composer update nosto/shopware6-job-scheduler

        pack:
            excludes:
                paths:
                    - .gitignore
                    - .github
                    - .git
                    - bin
                    - images
                    - node_modules
                    - tests
                    - ecs.php
                    - phpunit.xml.dist
                    - package.json
                    - package-lock.json
                    - .eslintignore
                    - .eslintrc-administration.js
                    - .eslintrc-storefront.js
                    - "*.zip"
                    - "*.DS_Store"
                    - dependencies
                    - vendor/nosto/shopware6-job-scheduler/.idea
                    - vendor/nosto/shopware6-job-scheduler/.github
                    - vendor/nosto/shopware6-job-scheduler/node_modules
