build:
    shopwareVersionConstraint: "~6.6.0"

    zip:
        pack:
            excludes:
                paths:
                    - .shopware-extension.yml
                    - .gitignore
                    - .github
                    - .git
                    - bin
                    - docs
                    - node_modules
                    - release
                    - tests
                    - vendor
                    - ecs.php
                    - phpunit.xml.dist
                    - package.json
                    - package-lock.json
                    - composer.lock
                    - .eslintignore
                    - .eslintrc-administration.js
                    - .eslintrc-storefront.js
                    - "*.zip"
                    - "*.DS_Store"
