build:
    shopwareVersionConstraint: "^6.5.4"

    zip:
        composer:
            before_hooks:
                - composer install --no-dev

        pack:
            excludes:
                paths:
                    - .shopware-extension.yml
                    - .gitignore
                    - .github
                    - .git
                    - bin
                    - docs
                    - node_modules
                    - tests
                    - vendor
                    - ecs.php
                    - phpunit.xml.dist
                    - package.json
                    - package-lock.json
                    - .eslintignore
                    - .eslintrc-administration.js
                    - .eslintrc-storefront.js
                    - .shopware-extension.yml
                    - "*.zip"
                    - "*.DS_Store"
