name: 'Setup runner'
description: 'Setup PHP and MySQL'
inputs:
  php-version:
    description: 'PHP version for PHP setup'
    required: true
    default: '8.1'

runs:
  using: 'composite'
  steps:
    - name: Setup PHP with Composer 2
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}"
        extensions: dom, gd, mbstring, pdo_mysql, zip
        coverage: xdebug
        tools: composer:v2

    - uses: mirromutth/mysql-action@v1.1
      with:
        mysql version: 8.0
        mysql database: shopware_test
        mysql root password: root

    - uses: actions/setup-node@v4
      with:
        node-version: 18.18.0 # Last version with npm 9 (Shopware requirement)

    - name: Install Shopware-CLI
      shell: bash
      run: |
        curl -1sLf "https://dl.cloudsmith.io/public/friendsofshopware/stable/setup.deb.sh" | sudo -E bash
        sudo apt install shopware-cli
