name: 'Setup runner'
description: 'A set of steps to perform a task'
inputs:
  php-version:
    description: 'PHP version for PHP setup'
    required: true
    default: 8.1
  mysql-version:
    description: 'PHP version for PHP setup'
    required: true
    default: 8.0

runs:
  using: 'composite'
  steps:
    - name: Setup PHP with Composer 2
      uses: shivammathur/setup-php@v2
      with:
        php-version: inputs.php-version
        extensions: dom, gd, mbstring, pdo_mysql, zip
        coverage: xdebug
        tools: composer:v2

    - uses: mirromutth/mysql-action@v1.1
      with:
        mysql version: 8.0
        mysql database: shopware_test
        mysql root password: root
