name: 'Setup plugin'
description: 'A set of steps to perform a task'
inputs:
  ssh-key:
    description: 'SSH Key'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Clone job scheduler repo
      uses: actions/checkout@v2
      with:
        repository: Nosto/shopware6-job-scheduler
        path: nosto-shopware6/dependencies/shopware6-job-scheduler
        ssh-key: ${{ inputs.ssh-key }}

    - name: Validate dependencies
      working-directory: nosto-shopware6
      shell: bash
      run: composer validate

    - name: Install plugin dependencies
      working-directory: nosto-shopware6
      shell: bash
      run: |
        npm ci
        composer install --no-interaction