name: 'Setup plugin'
description: 'Install and validate plugin dependencies'

runs:
  using: 'composite'
  steps:
    - name: Validate dependencies
      working-directory: nosto-shopware6
      shell: bash
      run: composer validate

    - name: Install plugin dependencies
      working-directory: nosto-shopware6
      shell: bash
      run: |
        npm ci
        composer install --no-interaction
