name: 'Setup shop'
description: 'Install the Shopware shop with plugin'
inputs:
  shopware-version:
    description: 'Version for the Shopware installation'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Create shop
      shell: bash
      run: shopware-cli project create shopware ${{ inputs.shopware-version }}

    - name: Set minimum stability to dev
      shell: bash
      run: |
        cd shopware
        composer config minimum-stability dev

    - name: Install Shopware
      shell: bash
      run: |
        cp nosto-shopware6/.github/.env.local shopware/.env.local
        cp nosto-shopware6/.github/.env.local shopware/.env.test
        cd shopware
        ./bin/console system:install --basic-setup

    - name: Install plugin
      shell: bash
      run: |
        cp -r nosto-shopware6 shopware/custom/plugins
        cd shopware
        php bin/console plugin:refresh
        php bin/console plugin:install --activate --clearCache NostoIntegration
