name: Lint JS

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    name: ESLint
    steps:
      - uses: actions/checkout@v2
        with:
          path: nosto-shopware6

      - name: Setup
        uses: ./.github/actions/setup_plugin
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Shopware dependencies
        working-directory: nosto-shopware6
        run: npm run install-sw-dependencies

      - name: Run ESLint
        working-directory: nosto-shopware6
        run: |
          npm run administration-lint
          npm run storefront-lint
