name: Lint JS

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    name: ESLint
    steps:
      - uses: actions/checkout@v2
        with:
          path: shopware6-plugin

      - name: Clone job scheduler repo
        uses: actions/checkout@v2
        with:
          repository: Nosto/shopware6-job-scheduler
          path: shopware6-plugin/dependencies/shopware6-job-scheduler
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup PHP with Composer 2
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: dom, gd, mbstring, pdo_mysql, zip
          coverage: xdebug
          tools: composer:v2

      - name: Validate dependencies
        working-directory: shopware6-plugin
        run: composer validate

      - name: Install plugin dependencies
        working-directory: shopware6-plugin
        run: |
          npm ci
          composer install --no-interaction

      - name: Install Shopware dependencies
        working-directory: shopware6-plugin
        run: npm run install-sw-dependencies

      - name: Run ESLint
        working-directory: shopware6-plugin
        run: |
          npm run administration-lint
          npm run storefront-lint
