name: Lint JS

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    name: ESLint
    steps:
      - uses: actions/checkout@v2
        with:
          path: nosto-shopware6

      - name: Setup Runner
        uses: ./nosto-shopware6/.github/action/setup_runner

      - name: Setup Plugin
        uses: ./nosto-shopware6/.github/action/setup_plugin
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup Shopware Shop
        uses: ./nosto-shopware6/.github/action/setup_shop
        with:
          shopware-version: '6.5.7.3'

      - name: Install administration dependencies
        run: |
          cd shopware/vendor/shopware/administration/Resources/app/administration
          npm i

      - name: Install storefront dependencies
        run: |
          cd shopware/vendor/shopware/storefront/Resources/app/storefront
          npm i

      - name: Run ESLint
        working-directory: nosto-shopware6
        run: |
          cd shopware/custom/plugins/nosto-shopware6
          npm run administration-lint
          npm run storefront-lint
