name: Lint PHP

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    name: PHPLint
    steps:
      - uses: actions/checkout@v2
        with:
          path: shopware6-plugin

      - name: Setup PHP with Composer 2
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: dom, gd, mbstring, pdo_mysql, zip
          coverage: xdebug
          tools: composer:v2

      - name: Validate dependencies
        working-directory: shopware6-plugin
        run: composer validate

      - name: Install plugin dependencies
        working-directory: shopware6-plugin
        run: composer install --no-interaction

      - name: Run ESLint
        working-directory: shopware6-plugin
        run: composer run lint
