name: Lint JS

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    uses: ./.github/workflows/shared-setup.yml

    name: ESLint
    steps:
      - name: Install plugin dependencies
        working-directory: nosto-shopware6
        run: |
          npm ci
          composer install --no-interaction

      - name: Install Shopware dependencies
        working-directory: nosto-shopware6
        run: npm run install-sw-dependencies

      - name: Run ESLint
        working-directory: nosto-shopware6
        run: |
          npm run administration-lint
          npm run storefront-lint
