name: Lint PHP

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    uses: ./.github/workflows/shared-setup.yml

    name: PHPLint
    steps:
      - name: Install plugin dependencies
        working-directory: nosto-shopware6
        run: composer install --no-interaction

      - name: Run PHPLint
        working-directory: nosto-shopware6
        run: composer run lint
