name: Lint JS

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    name: ESLint
    steps:
      - uses: actions/checkout@v4
        with:
          path: nosto-shopware6

      - name: Setup Runner
        uses: ./nosto-shopware6/.github/action/setup_runner

      - name: Configure Composer audit behaviour
        run: >-
          composer config --global --json audit.ignore
          '["PKSA-b824-t6kf-bqqz","PKSA-6wp3-462p-vyty","PKSA-h5dj-jyqc-4fjr","PKSA-kypv-cx5n-qkc8","PKSA-v415-g75g-bqsy","PKSA-8vfm-96b7-t9nt","PKSA-m54b-2v2z-x1bs","PKSA-frt7-rv6d-9v53","PKSA-dbxn-psgm-2qmr","PKSA-k472-zz4q-rd5r","PKSA-kt1g-n1g2-hzb4","PKSA-wp2c-7yp8-5fvs","PKSA-4spx-rq41-wk8h","PKSA-6stq-czfs-1nvv"]'
          && composer config --global audit.block-insecure false

      - name: Setup Plugin
        uses: ./nosto-shopware6/.github/action/setup_plugin

      - name: Setup Shopware Shop
        uses: ./nosto-shopware6/.github/action/setup_shop
        with:
          shopware-version: '6.6.2.0'

      - name: Install administration dependencies
        run: |
          cd shopware/vendor/shopware/administration/Resources/app/administration
          npm i

      - name: Install storefront dependencies
        run: |
          cd shopware/vendor/shopware/storefront/Resources/app/storefront
          npm i

      - name: Run ESLint
        run: |
          cd shopware/custom/plugins/nosto-shopware6
          npm run administration-lint
          npm run storefront-lint
