name: Lint PHP

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    name: PHPLint
    steps:
      - uses: actions/checkout@v2
        with:
          path: nosto-shopware6

      - name: Setup
        uses: ./.github/actions/setup_plugin
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run PHPLint
        working-directory: nosto-shopware6
        run: composer run lint
