name: Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [ '8.2', '8.3' ]
        shopware-versions: [
          '6.6.0.3',
          '6.6.1.2',
          '6.6.2.0',
        ]

    name: Shopware ${{ matrix.shopware-versions }} Test (PHP ${{ matrix.php-versions }})
    steps:
      - uses: actions/checkout@v4
        with:
          path: nosto-shopware6

      - name: Setup Runner
        uses: ./nosto-shopware6/.github/action/setup_runner
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Configure Composer audit behaviour
        run: >-
          composer config --global --json audit.ignore
          '["PKSA-b824-t6kf-bqqz","PKSA-6wp3-462p-vyty","PKSA-h5dj-jyqc-4fjr","PKSA-kypv-cx5n-qkc8","PKSA-v415-g75g-bqsy","PKSA-8vfm-96b7-t9nt","PKSA-m54b-2v2z-x1bs","PKSA-frt7-rv6d-9v53","PKSA-dbxn-psgm-2qmr","PKSA-k472-zz4q-rd5r","PKSA-kt1g-n1g2-hzb4","PKSA-wp2c-7yp8-5fvs","PKSA-4spx-rq41-wk8h","PKSA-6stq-czfs-1nvv"]'
          && composer config --global audit.block-insecure false

      - name: Setup Plugin
        uses: ./nosto-shopware6/.github/action/setup_plugin

      - name: Setup Shopware Shop
        uses: ./nosto-shopware6/.github/action/setup_shop
        with:
          shopware-version: ${{ matrix.shopware-versions }}

      - name: Install test dependencies for SW
        run: |
          cd shopware
          composer require --dev symfony/test-pack

      - name: Run PHPUnit test suite
        run: |
          cd shopware/custom/plugins/nosto-shopware6
          SYMFONY_DEPRECATIONS_HELPER=disabled composer test
